name: dashboard-ocr
dependencies:
  - python=3.6
  - pip:
    - pandas
    - pymysql
    - flask
    - pyecharts
    - openpyxl
    - pylint
    - yapf
    - numpy
    - torch>=1.0
    - torchvision
    - matplotlib
    - tensorflow
    - tensorboard
    - terminaltables
    - pillow
    - tqdm